using System;

namespace Nova.Simulation.Factions
{
    /// <summary>
    /// Deterministic 2D grid tracking organic Biomass spread generated by Evolved buildings.
    /// Evolved units gain passive health regeneration while positioned on Biomass cells.
    /// Zero engine dependencies (no UnityEngine types).
    /// </summary>
    public sealed class BiomassGrid
    {
        private readonly bool[] _biomassCells;

        public ushort Width { get; }
        public ushort Height { get; }

        public BiomassGrid(ushort width = 128, ushort height = 128)
        {
            Width = width;
            Height = height;
            _biomassCells = new bool[width * height];
        }

        public bool HasBiomass(ushort x, ushort y)
        {
            if (x >= Width || y >= Height) return false;
            return _biomassCells[y * Width + x];
        }

        public bool IsOnBiomass(float worldX, float worldY)
        {
            if (worldX < 0f || worldY < 0f) return false;
            ushort x = (ushort)Math.Floor(worldX);
            ushort y = (ushort)Math.Floor(worldY);
            return HasBiomass(x, y);
        }

        public void SetBiomassCircle(ushort centerX, ushort centerY, ushort radius)
        {
            int minX = Math.Max(0, centerX - radius);
            int maxX = Math.Min(Width - 1, centerX + radius);
            int minY = Math.Max(0, centerY - radius);
            int maxY = Math.Min(Height - 1, centerY + radius);

            int rSq = radius * radius;

            for (int y = minY; y <= maxY; y++)
            {
                int dy = y - centerY;
                for (int x = minX; x <= maxX; x++)
                {
                    int dx = x - centerX;
                    if (dx * dx + dy * dy <= rSq)
                    {
                        _biomassCells[y * Width + x] = true;
                    }
                }
            }
        }
    }
}
